import Product1 from "../../assets/icons/discord.svg";
import Product2 from "../../assets/icons/discord.svg";
import Assets from "../../assets/icons/discord.svg";
import { IProduct } from ".";
import { useSelector, useDispatch } from "react-redux";

const products: IProduct[] = [
    {
        secId: "FTECHSR420",
        secName: "A Fintech SR 11% 2023",
        apy: "11.21",
        frequency: "Monthly",
        maturity: "Dec 23",
        issuer: "Cauris Finance",
        totalIssuance: "$5MM",
        availableIssuance: "$1.2MM",
        category: "Revenue based/Invoice Discounting",
        ltv: "0.8",
        leverage: "3.0",
        moreInfo: "MoreInfo",
    },
    // {
    //     secId: "FTECHSR420",
    //     secName: "A Fintech SR 11% 2023",
    //     apy: "11.21",
    //     frequency: "Monthly",
    //     maturity: "Dec 23",
    //     issuer: "Awesome Fintech",
    //     totalIssuance: "$5MM",
    //     availableIssuance: "$1.2MM",
    //     category: "Revenue based/Invoice Discounting",
    //     ltv: "0.8",
    //     leverage: "3.0",
    //     moreInfo: "MoreInfo",
    // },
    // {
    //     secId: "FTECHSR420",
    //     secName: "A Fintech SR 11% 2023",
    //     apy: "11.21",
    //     frequency: "Monthly",
    //     maturity: "Dec 23",
    //     issuer: "Awesome Fintech",
    //     totalIssuance: "$5MM",
    //     availableIssuance: "$1.2MM",
    //     category: "Revenue based/Invoice Discounting",
    //     ltv: "0.8",
    //     leverage: "3.0",
    //     moreInfo: "MoreInfo",
    // },
    // {
    //     secId: "FTECHSR420",
    //     secName: "A Fintech SR 11% 2023",
    //     apy: "11.21",
    //     frequency: "Monthly",
    //     maturity: "Dec 23",
    //     issuer: "Awesome Fintech",
    //     totalIssuance: "$5MM",
    //     availableIssuance: "$1.2MM",
    //     category: "Revenue based/Invoice Discounting",
    //     ltv: "0.8",
    //     leverage: "3.0",
    //     moreInfo: "MoreInfo",
    // },
    // {
    //     secId: "FTECHSR420",
    //     secName: "A Fintech SR 11% 2023",
    //     apy: "11.21",
    //     frequency: "Monthly",
    //     maturity: "Dec 23",
    //     issuer: "Awesome Fintech",
    //     totalIssuance: "$5MM",
    //     availableIssuance: "$1.2MM",
    //     category: "Revenue based/Invoice Discounting",
    //     ltv: "0.8",
    //     leverage: "3.0",
    //     moreInfo: "MoreInfo",
    // },
    // {
    //     secId: "FTECHSR420",
    //     secName: "A Fintech SR 11% 2023",
    //     apy: "11.21",
    //     frequency: "Monthly",
    //     maturity: "Dec 23",
    //     issuer: "Awesome Fintech",
    //     totalIssuance: "$5MM",
    //     availableIssuance: "$1.2MM",
    //     category: "Revenue based/Invoice Discounting",
    //     ltv: "0.8",
    //     leverage: "3.0",
    //     moreInfo: "MoreInfo",
    // },
    // {
    //     secId: "FTECHSR420",
    //     secName: "A Fintech SR 11% 2023",
    //     apy: "11.21",
    //     frequency: "Monthly",
    //     maturity: "Dec 23",
    //     issuer: "Awesome Fintech",
    //     totalIssuance: "$5MM",
    //     availableIssuance: "$1.2MM",
    //     category: "Revenue based/Invoice Discounting",
    //     ltv: "0.8",
    //     leverage: "3.0",
    //     moreInfo: "MoreInfo",
    // },
];

export default products;
